kango.KangoBrowserCookie=function(){this.path=this.hostOnly=this.domain=this.value=this.name="";this.session=this.httpOnly=this.secure=!1;this.expires=0};kango.BrowserBase=function(){kango.oop.mixin(this,kango.EventTarget.prototype);kango.oop.mixin(this,new kango.EventTarget)};
kango.BrowserBase.prototype={event:{DOCUMENT_COMPLETE:"DocumentComplete",BEFORE_NAVIGATE:"BeforeNavigate",TAB_CHANGED:"TabChanged",TAB_CREATED:"TabCreated",TAB_REMOVED:"TabRemoved",WINDOW_CHANGED:"WindowChanged"},getName:function(){throw new kango.NotImplementedException;},cookies:{getCookies:function(a,b){throw new kango.NotImplementedException;},getCookie:function(a,b,c){throw new kango.NotImplementedException;},setCookie:function(a,b){throw new kango.NotImplementedException;}},tabs:{getAll:function(a){throw new kango.NotImplementedException;
},getCurrent:function(a){throw new kango.NotImplementedException;},create:function(a){throw new kango.NotImplementedException;}},windows:{getAll:function(a){throw new kango.NotImplementedException;},getCurrent:function(a){throw new kango.NotImplementedException;},create:function(a){throw new kango.NotImplementedException;}}};kango.IBrowserWindow=function(){};
kango.IBrowserWindow.prototype={getId:function(){throw new kango.NotImplementedException;},getTabs:function(a){throw new kango.NotImplementedException;},getCurrentTab:function(a){throw new kango.NotImplementedException;},isActive:function(){throw new kango.NotImplementedException;}};kango.IBrowserTab=function(){};
kango.IBrowserTab.prototype={getId:function(){throw new kango.NotImplementedException;},getUrl:function(){throw new kango.NotImplementedException;},getTitle:function(){throw new kango.NotImplementedException;},getDOMWindow:function(){throw new kango.NotImplementedException;},isActive:function(){throw new kango.NotImplementedException;},isPrivate:function(){throw new kango.NotImplementedException;},navigate:function(a){throw new kango.NotImplementedException;},activate:function(){throw new kango.NotImplementedException;
},dispatchMessage:function(a,b){throw new kango.NotImplementedException;},close:function(){throw new kango.NotImplementedException;}};








kango.ObjectTracker=function(){this._lastId=0;this._objs={}};kango.ObjectTracker.prototype={_objs:null,_lastId:null,_geNextId:function(){return this._lastId++},add:function(a){var b=this.getId(a);return-1==b?(b=this._geNextId(),this._objs[b]=a,b):-1},remove:function(a){a=this.getId(a);return-1!=a?delete this._objs[a]:!1},getId:function(a){for(var b in this._objs)if(this._objs.hasOwnProperty(b)&&this._objs[b]===a)return b;return-1}};
kango.Browser=function(){this.superclass.apply(this,arguments);this._tabTracker=new kango.ObjectTracker;this._windowTracker=new kango.ObjectTracker;safari.application.addEventListener("beforeNavigate",kango.func.bind(this._onBeforeNavigate,this),!0);safari.application.addEventListener("navigate",kango.func.bind(this._onNavigate,this),!0);safari.application.addEventListener("activate",kango.func.bind(this._onActivate,this),!0);safari.application.addEventListener("open",kango.func.bind(this._onOpen,
this),!0);safari.application.addEventListener("close",kango.func.bind(this._onClose,this),!0)};
kango.Browser.prototype=kango.oop.extend(kango.BrowserBase,{_tabTracker:null,_windowTracker:null,_onOpen:function(a){a.target instanceof SafariBrowserTab&&(a=this.getKangoTab(a.target),kango.browser.fireEvent(this.event.TAB_CREATED,{target:a,tabId:a.getId()}))},_onClose:function(a){a.target instanceof SafariBrowserTab?(a=a.target,this.fireEvent(this.event.TAB_REMOVED,{tabId:this._tabTracker.getId(a)}),this._tabTracker.remove(a)):a.target instanceof SafariBrowserWindow&&this._windowTracker.remove(a.target)},
_onActivate:function(a){a.target instanceof SafariBrowserTab?(a=this.getKangoTab(a.target),kango.browser.fireEvent(this.event.TAB_CHANGED,{url:a.getUrl(),title:a.getTitle(),target:a,tabId:a.getId()})):a.target instanceof SafariBrowserWindow&&this.fireEvent(this.event.WINDOW_CHANGED,{target:this.getKangoWindow(a.target)})},_onBeforeNavigate:function(a){var b=this.getKangoTab(a.target);this.fireEvent(this.event.BEFORE_NAVIGATE,{url:a.url||"",target:b})},_onNavigate:function(a){a=this.getKangoTab(a.target);
this.fireEvent(this.event.DOCUMENT_COMPLETE,{url:a.getUrl(),title:a.getTitle(),target:a})},getKangoTab:function(a){var b=this._tabTracker.getId(a);-1==b&&(b=this._tabTracker.add(a));return new kango.BrowserTab(a,b)},getKangoWindow:function(a){var b=this._windowTracker.getId(a);-1==b&&(b=this._windowTracker.add(a));return new kango.BrowserWindow(a,b)},getName:function(){return"safari"},windows:{getAll:function(a){a(kango.array.map(safari.application.browserWindows,function(a){return kango.browser.getKangoWindow(a)}))},
getCurrent:function(a){a(kango.browser.getKangoWindow(safari.application.activeBrowserWindow))},create:function(a){safari.application.openBrowserWindow().activeTab.url=a.url}},tabs:{getAll:function(a){for(var b=[],e=safari.application.browserWindows,c=0;c<e.length;c++)for(var f=e[c].tabs,d=0;d<f.length;d++)b.push(kango.browser.getKangoTab(f[d]));a(b)},getCurrent:function(a){a(kango.browser.getKangoTab(safari.application.activeBrowserWindow.activeTab))},create:function(a){safari.application.activeBrowserWindow.openTab(("undefined"!=
typeof a.focused?a.focused:1)?"foreground":"background").url=a.url}}});kango.BrowserWindow=function(a,b){this._window=a;this._id=b};
kango.BrowserWindow.prototype=kango.oop.extend(kango.IBrowserWindow,{_window:null,_id:null,getId:function(){return this._id},getTabs:function(a){a(kango.array.map(this._window.tabs,function(a){return kango.browser.getKangoTab(a)}))},getCurrentTab:function(a){a(kango.browser.getKangoTab(this._window.activeTab))},isActive:function(){return safari.application.activeBrowserWindow==this._window}});kango.BrowserTab=function(a,b){this._tab=a;this._id=b};
kango.BrowserTab.prototype=kango.oop.extend(kango.IBrowserTab,{_id:null,_tab:null,getId:function(){return this._id},getUrl:function(){return this._tab.url||""},getTitle:function(){return this._tab.title||""},getDOMWindow:function(){return null},isActive:function(){return this._tab==this._tab.browserWindow.activeTab},isPrivate:function(){return"undefined"!=typeof safari.application.privateBrowsing?safari.application.privateBrowsing.enabled:!1},navigate:function(a){this._tab.url=a},activate:function(){var a=
this._tab.browserWindow;safari.application.activeBrowserWindow!=a&&a.activate();a.activeTab!=this._tab&&this._tab.activate()},dispatchMessage:function(a,b){return"undefined"!=typeof this._tab.page?(this._tab.page.dispatchMessage(a,b),!0):!1},close:function(){this._tab.close()}});kango.browser=new kango.Browser;
