kango.IStorage=function(){};kango.IStorage.prototype={setItem:function(a,b){throw new kango.NotImplementedException;},getItem:function(a){throw new kango.NotImplementedException;},removeItem:function(a){throw new kango.NotImplementedException;},getKeys:function(){throw new kango.NotImplementedException;},clear:function(){throw new kango.NotImplementedException;}};kango.JSONStorage=function(a){this._storageEngine=a};
kango.JSONStorage.prototype=kango.oop.extend(kango.IStorage,{_storageEngine:null,getItem:function(a){a=this._storageEngine.getItem(a);return"undefined"!=typeof a&&null!=a?JSON.parse(a):null},setItem:function(a,b){if("undefined"!=typeof b){var c=JSON.stringify(b);if("undefined"!=typeof c)return this._storageEngine.setItem(a,c)}else return this.removeItem(a);return!1},removeItem:function(a){return this._storageEngine.removeItem(a)},getKeys:function(){return this._storageEngine.getKeys()},clear:function(){return this._storageEngine.clear()},
dispose:function(){"undefined"!=typeof this._storageEngine.dispose&&this._storageEngine.dispose();this._storageEngine=null}});








kango.LocalStorage=function(){var a="http://"+this._getDomainFromId(kango.getExtensionInfo().id)+".kangoextensions.com";this._storage=this._getLocalStorageForUrl(a)};
kango.LocalStorage.prototype={_storage:null,_getDomainFromId:function(a){for(var b="",c=0;c<a.length;c++)if(kango.string.isAlpha(a[c])||kango.string.isDigit(a[c])||"-"==a[c])b+=a[c];return b},_getLocalStorageForUrl:function(a){var b=Services.scriptSecurityManager||Cc["@mozilla.org/scriptsecuritymanager;1"].getService(Components.interfaces.nsIScriptSecurityManager);a=Services.io.newURI(a,null,null);b=b.getNoAppCodebasePrincipal?b.getNoAppCodebasePrincipal(a):b.getCodebasePrincipal(a);return(Services.domStorageManager||
Cc["@mozilla.org/dom/storagemanager;1"].getService(Components.interfaces.nsIDOMStorageManager)).getLocalStorageForPrincipal(b,"")},getItem:function(a){return this._storage.getItem(a)},setItem:function(a,b){this._storage.setItem(a,b)},removeItem:function(a){this._storage.removeItem(a)},clear:function(){this._storage.clear()},getKeys:function(){for(var a=this._storage.length,b=Array(a),c=0;c<a;c++)b[c]=this._storage.key(c);return b}};
kango.SQLiteStorageAsync=function(a){this._tableName=a+"_storage";this._connect=this._openDatabase();this._createDatabase()};
kango.SQLiteStorageAsync.prototype={_tableName:null,_connect:null,_getDatabaseFile:function(){var a=kango.getExtensionInfo().package_id+".sqlite";return FileUtils.getFile("ProfD",[a])},_openDatabase:function(){var a=this._getDatabaseFile();return Services.storage.openDatabase(a)},_createDatabase:function(){this._connect.executeSimpleSQL("CREATE TABLE IF NOT EXISTS "+this._tableName+" (key TEXT PRIMARY KEY, value TEXT)")},getItems:function(a){var b={};this._connect.createStatement("SELECT key, value FROM "+
this._tableName).executeAsync({handleResult:function(a){for(var d=a.getNextRow();d;){var e=d.getResultByName("key");b[e]=d.getResultByName("value");d=a.getNextRow()}},handleError:function(a){},handleCompletion:function(c){a(b)}})},setItem:function(a,b,c){var d=this._connect.createStatement("INSERT OR REPLACE INTO "+this._tableName+" (key, value) VALUES(:key, :value)");d.params.key=a;d.params.value=b.toString();d.executeAsync({handleResult:function(a){},handleError:function(a){},handleCompletion:function(a){"function"==
typeof c&&c(a==Ci.mozIStorageStatementCallback.REASON_FINISHED)}})},removeItem:function(a,b){var c=this._connect.createStatement("DELETE FROM "+this._tableName+" WHERE key=:key");c.params.key=a;c.executeAsync({handleResult:function(a){},handleError:function(a){},handleCompletion:function(a){"function"==typeof b&&b(a==Ci.mozIStorageStatementCallback.REASON_FINISHED)}})},clear:function(a){this._connect.createStatement("DELETE FROM "+this._tableName).executeAsync({handleResult:function(a){},handleError:function(a){},
handleCompletion:function(b){"function"==typeof a&&a(b==Ci.mozIStorageStatementCallback.REASON_FINISHED)}})},close:function(){null!=this._connect&&(this._connect.asyncClose(),this._connect=null)},dispose:function(){this.close()},removeDatabase:function(){this.close();this._getDatabaseFile().remove(!1)}};kango.SQLiteStorageAsyncCache=function(){this._data={}};
kango.SQLiteStorageAsyncCache.prototype={_data:{},setItems:function(a){this._data=a},getItem:function(a){return this._data[a]||null},setItem:function(a,b){this._data[a]=b},removeItem:function(a){return delete this._data[a]},clear:function(){this._data={}},getKeys:function(){return kango.object.getKeys(this._data)}};
kango.SQLiteStorage=function(a){var b=this;kango.registerAsyncModuleInitializer(b);this._storage=a;var c=this._cache=new kango.SQLiteStorageAsyncCache;a.getItems(function(a){c.setItems(a);kango.fireEvent(kango.event.ASYNC_MODULE_INITIALIZED,{data:b})})};
kango.SQLiteStorage.prototype={_storage:null,_cache:null,getItem:function(a){return this._cache.getItem(a)},setItem:function(a,b){this._cache.setItem(a,b);this._storage.setItem(a,b)},removeItem:function(a){this._cache.removeItem(a);this._storage.removeItem(a)},clear:function(){this._cache.clear();this._storage.clear()},getKeys:function(){return this._cache.getKeys()},dispose:function(){this._storage.dispose();this._cache=this._storage=null}};kango.Storage=function(){return new kango.SQLiteStorage(new kango.SQLiteStorageAsync("user"))};
kango.SystemStorage=function(){return new kango.SQLiteStorage(new kango.SQLiteStorageAsync("system"))};kango.registerModule(kango.getDefaultModuleRegistrar("storage",function(){return new kango.JSONStorage(new kango.Storage)}));kango.registerModule(kango.getDefaultModuleRegistrar("systemStorage",function(){return new kango.JSONStorage(new kango.SystemStorage)}));
kango.registerModule(function(){var a=new kango.JSONStorage(new kango.LocalStorage),b=a.getKeys();0<b.length&&(kango.array.forEach(b,function(b){kango.storage.setItem(b,a.getItem(b))}),a.clear())});
